apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmctld
  name: slurmctld
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmctld
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: slurmctld
    spec:
      containers:
        - env:
            - name: SLURM_CLUSTER_NAME
              value: ikimslurm
            - name: SLURM_CONTROL_MACHINE
              value: slurmctld
            - name: SLURM_NODE_NAMES
              value: slurmd
          image: ryade/slurmbase
          name: slurmctld
          ports:
            - containerPort: 6817
          resources: {}
          stdin: true
          tty: true
      hostname: slurmctld
      restartPolicy: Always
status: {}
