version: '2'

services:
  slurmctld:
    container_name: slurmctld
    environment:
      SLURM_CLUSTER_NAME: ikimslurm
      SLURM_CONTROL_MACHINE: slurmctld
      SLURM_NODE_NAMES: slurmd
    tty: true
    hostname: slurmctld
    networks:
      default:
        aliases:
          - slurmctld
    image: ryade/slurmbase 
    stdin_open: true
  slurmd:
    container_name: slurmd
    environment:
      SLURM_CONTROL_MACHINE: slurmctld
      SLURM_CLUSTER_NAME: ikimslurm
      SLURM_NODE_NAMES: slurmd
    tty: true
    hostname: slurmd
    networks:
      default:
        aliases:
          - slurmd
    image: ryade/slurmbase 
    depends_on:
      - slurmctld
    stdin_open: true
